# Generated by Django 4.0.2 on 2022-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('', 'Select category'), ('programming', 'Programming'), ('sci and tech', 'Science and Tech'), ('health', 'Health')], default=23, max_length=25),
            preserve_default=False,
        ),
    ]
